[brainflow]
timeout = 30
; ip_port = 
; ip_protocol = 
; ip_address =
; serial_port =
; mac_address =
; other_info =
; streamer_params =
; serial_number =
; file =
board_id = 

[application]
window_seconds = 1
refresh_rate = 60
ema_decay = 1.0
retry_count = 60
sensitivity = 1.1

[osc]
ip_address = 127.0.0.1
port = 9000
use_old_reporter = false

[debug]
debug = false
enable_logs = false

[action]
enable_action = false
action_ema_multiplier = 5.0
